# Generated by Django 3.2.20 on 2023-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=200, unique=True)),
                ('class_address', models.CharField(max_length=200)),
                ('class_day', models.CharField(max_length=200)),
                ('class_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
