# Generated by Django 3.2.20 on 2023-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_county',
            field=models.CharField(max_length=50),
        ),
    ]
