# Generated by Django 3.2.20 on 2023-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_class_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
