# Generated by Django 3.2.20 on 2023-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_first_name', models.CharField(default='user', max_length=50)),
                ('member_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('member_email_address', models.EmailField(max_length=254)),
                ('class_choice', models.CharField(max_length=50)),
            ],
        ),
    ]
