# Generated by Django 3.2.20 on 2023-07-31 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success_Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('weight_loss', models.IntegerField()),
                ('start_weight', models.IntegerField()),
                ('weight_now', models.IntegerField()),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('class_attended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes')),
            ],
        ),
    ]
